dist: focal

jobs:
  include:
    - stage: Echo
      script: 
        - echo "TRAVIS_PULL_REQUEST_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH} TRAVIS_BRANCH=${TRAVIS_BRANCH} TRAVIS_COMMIT_RANGE=${TRAVIS_COMMIT_RANGE} TRAVIS_COMMIT_RANGE=${TRAVIS_COMMIT_RANGE}"
        - repo_url=$(git config --get remote.origin.url)
        - latestPRCommit=(${TRAVIS_COMMIT_RANGE//\.\.\./ })
        - latestPRCommit=${latestPRCommit[1]}
        - git clone ${repo_url} ${latestPRCommit}
        - cd ${latestPRCommit}
        - SOURCE_BRANCH=($(git branch -r --contains ${latestPRCommit}))
        - export SOURCE_BRANCH=${SOURCE_BRANCH/origin\//}
        - echo "SOURCE_BRANCH=${SOURCE_BRANCH}"
        - cd -
